language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
  - pipenv install pytest --skip-lock
  - pipenv install pytest-cov --skip-lock
  - pipenv install codecov --skip-lock

# command to run tests
script:
  - pytest --cov=./
after_success:
  - codecov
